import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { promisify } from "node:util";

import type { CryptoRailId, FiatCurrencyCode } from "@sdp/types/payment-rails";
import { RAMP_PROVIDERS, type RampProviderId } from "@sdp/types/provider-access";

const execFileAsync = promisify(execFile);

const GENERATED_RELATIVE_PATH = "packages/sdp-types/src/generated/ramp-support.generated.ts";
const GENERATED_PATH = path.resolve(process.cwd(), "../../", GENERATED_RELATIVE_PATH);
const COMMENT_PATH = path.resolve(process.cwd(), ".ramp-rails/ramp-rails-drift-comment.md");
const COMMENT_MARKER = "<!-- sdp-ramp-rails-drift -->";
const CANDIDATE_GENERATED_PATH = process.env.RAMP_RAILS_CANDIDATE_GENERATED_PATH?.trim();

interface GeneratedOnrampRow {
  source: FiatCurrencyCode;
  dest: CryptoRailId;
  providers: readonly RampProviderId[];
}

interface GeneratedOfframpRow {
  source: CryptoRailId;
  dest: FiatCurrencyCode;
  providers: readonly RampProviderId[];
}

interface GeneratedRampSupportModule {
  RAMP_SUPPORT_HASH?: string;
  RAMP_PROVIDER_SUPPORT_HASHES?: Partial<Record<RampProviderId, string>>;
  ONRAMP_SUPPORT: readonly GeneratedOnrampRow[];
  OFFRAMP_SUPPORT: readonly GeneratedOfframpRow[];
}

interface ProviderPairs {
  onramp: string[];
  offramp: string[];
}

interface ProviderDiff {
  provider: RampProviderId;
  baseHash: string;
  currentHash: string;
  base: ProviderPairs;
  current: ProviderPairs;
  addedOnramp: string[];
  removedOnramp: string[];
  addedOfframp: string[];
  removedOfframp: string[];
}

interface CandidateGeneratedStatus {
  provided: boolean;
  exists: boolean;
  matchesCurrent: boolean;
}

function sha256Json(value: unknown): string {
  return createHash("sha256").update(JSON.stringify(value)).digest("hex");
}

function diffArrays(
  base: readonly string[],
  current: readonly string[]
): {
  added: string[];
  removed: string[];
} {
  const baseSet = new Set(base);
  const currentSet = new Set(current);
  return {
    added: current.filter((value) => !baseSet.has(value)),
    removed: base.filter((value) => !currentSet.has(value)),
  };
}

function pairsByProvider(
  module: GeneratedRampSupportModule
): Record<RampProviderId, ProviderPairs> {
  const byProvider = Object.fromEntries(
    RAMP_PROVIDERS.map((provider) => [provider, { onramp: [], offramp: [] }])
  ) as Record<RampProviderId, ProviderPairs>;

  for (const row of module.ONRAMP_SUPPORT) {
    for (const provider of row.providers) {
      byProvider[provider].onramp.push(`${row.source} -> ${row.dest}`);
    }
  }

  for (const row of module.OFFRAMP_SUPPORT) {
    for (const provider of row.providers) {
      byProvider[provider].offramp.push(`${row.source} -> ${row.dest}`);
    }
  }

  for (const provider of RAMP_PROVIDERS) {
    byProvider[provider].onramp.sort();
    byProvider[provider].offramp.sort();
  }

  return byProvider;
}

function providerHash(module: GeneratedRampSupportModule, provider: RampProviderId): string {
  const explicitHash = module.RAMP_PROVIDER_SUPPORT_HASHES?.[provider];
  if (explicitHash) return explicitHash;
  return sha256Json(pairsByProvider(module)[provider]);
}

async function importGeneratedModule(filePath: string): Promise<GeneratedRampSupportModule> {
  const fileUrl = pathToFileURL(filePath);
  return (await import(
    `${fileUrl.href}?t=${Date.now()}-${Math.random()}`
  )) as GeneratedRampSupportModule;
}

async function readBaseGeneratedSource(): Promise<string> {
  const baseRef = process.env.RAMP_RAILS_BASE_REF?.trim() || "HEAD";
  try {
    const { stdout } = await execFileAsync("git", [
      "show",
      `${baseRef}:${GENERATED_RELATIVE_PATH}`,
    ]);
    return stdout;
  } catch {
    // Local smoke tests before the generated file is committed should still run.
    return readFile(GENERATED_PATH, "utf8");
  }
}

async function readCandidateGeneratedSource(): Promise<string | undefined> {
  if (!CANDIDATE_GENERATED_PATH) return undefined;
  try {
    return await readFile(path.resolve(process.cwd(), CANDIDATE_GENERATED_PATH), "utf8");
  } catch {
    return undefined;
  }
}

function generatedSourcesMatch(left: string, right: string): boolean {
  return left.replace(/\r\n/g, "\n") === right.replace(/\r\n/g, "\n");
}

function buildComment(
  diffs: readonly ProviderDiff[],
  candidateStatus?: CandidateGeneratedStatus
): string {
  const lines = [
    COMMENT_MARKER,
    "## Ramp Rails Drift Detected",
    "",
    "Live provider rail data differs from the generated ramp support expected for this PR.",
    "If this drift is expected, run `pnpm --filter @sdp/api rails:discover --emit` and commit the generated file.",
    "",
  ];

  if (candidateStatus?.provided) {
    lines.push(
      candidateStatus.exists
        ? "The PR generated file does not match the live provider data generated by trusted CI code."
        : "The PR does not include the generated ramp support file.",
      ""
    );
  }

  if (diffs.length === 0) {
    lines.push("Provider support is unchanged from the base branch.");
    return `${lines.join("\n")}\n`;
  }

  lines.push(`Provider support drift detected for ${diffs.length} provider(s).`);

  return `${lines.join("\n")}\n`;
}

async function setGithubOutput(values: Record<string, string>): Promise<void> {
  const outputPath = process.env.GITHUB_OUTPUT;
  if (!outputPath) return;
  await writeFile(
    outputPath,
    `${Object.entries(values)
      .map(([key, value]) => `${key}=${value}`)
      .join("\n")}\n`,
    { flag: "a" }
  );
}

async function main(): Promise<void> {
  const generatedDir = path.dirname(GENERATED_PATH);
  const baseTempPath = path.join(generatedDir, `.ramp-support.base-${process.pid}.generated.ts`);
  const baseSource = await readBaseGeneratedSource();
  await writeFile(baseTempPath, baseSource, "utf8");

  try {
    const [baseModule, currentModule, currentSource, candidateSource] = await Promise.all([
      importGeneratedModule(baseTempPath),
      importGeneratedModule(GENERATED_PATH),
      readFile(GENERATED_PATH, "utf8"),
      readCandidateGeneratedSource(),
    ]);
    const basePairs = pairsByProvider(baseModule);
    const currentPairs = pairsByProvider(currentModule);
    const diffs: ProviderDiff[] = [];

    for (const provider of RAMP_PROVIDERS) {
      const baseHash = providerHash(baseModule, provider);
      const currentHash = providerHash(currentModule, provider);
      if (baseHash === currentHash) continue;

      const onrampDiff = diffArrays(basePairs[provider].onramp, currentPairs[provider].onramp);
      const offrampDiff = diffArrays(basePairs[provider].offramp, currentPairs[provider].offramp);
      diffs.push({
        provider,
        baseHash,
        currentHash,
        base: basePairs[provider],
        current: currentPairs[provider],
        addedOnramp: onrampDiff.added,
        removedOnramp: onrampDiff.removed,
        addedOfframp: offrampDiff.added,
        removedOfframp: offrampDiff.removed,
      });
    }

    const candidateStatus: CandidateGeneratedStatus | undefined = CANDIDATE_GENERATED_PATH
      ? {
          provided: true,
          exists: candidateSource !== undefined,
          matchesCurrent:
            candidateSource !== undefined && generatedSourcesMatch(candidateSource, currentSource),
        }
      : undefined;
    const hasChanges = candidateStatus ? !candidateStatus.matchesCurrent : diffs.length > 0;

    await mkdir(path.dirname(COMMENT_PATH), { recursive: true });
    if (hasChanges) {
      await writeFile(COMMENT_PATH, buildComment(diffs, candidateStatus), "utf8");
      await setGithubOutput({ has_changes: "true", comment_path: COMMENT_PATH });
      console.log(`Ramp rails drift detected for ${diffs.length} provider(s).`);
    } else {
      await writeFile(COMMENT_PATH, "", "utf8");
      await setGithubOutput({ has_changes: "false", comment_path: COMMENT_PATH });
      console.log("No ramp rails drift detected.");
    }
  } finally {
    await unlink(baseTempPath).catch(() => undefined);
  }
}

void main();
