import { z } from "zod";
import {
  badRequest,
  conflict,
  internalError,
  providerNotConfigured,
  providerUnavailable,
  rateLimited,
  type SdpPaymentsError,
} from "../../../errors";
import { bvnkErrorEnvelopeSchema } from "./schemas";

/**
 * A CloudFront/WAF edge rejection returns a non-JSON HTML body ("Request blocked",
 * "Generated by cloudfront") rather than BVNK's JSON error envelope. This means the
 * request never reached BVNK's app, so it's an availability/rate-limit issue — not a
 * credential problem — and must not be reported as a Hawk misconfiguration.
 */
function isEdgeBlockBody(parsed: unknown, raw: string): boolean {
  if (parsed !== undefined) return false;
  return /cloudfront|request could not be satisfied|request blocked/i.test(raw);
}

/**
 * Normalizes a BVNK non-2xx status into an SdpPaymentsError. Auth failures point at our
 * Hawk credential configuration, rate limits surface as-is, and any 5xx is a
 * BVNK-side failure operators should investigate rather than a bad request body.
 */
function mapBvnkErrorStatus(
  status: number,
  message: string,
  options?: { edgeBlocked?: boolean; details?: Record<string, unknown> }
): SdpPaymentsError {
  if (options?.edgeBlocked) {
    return providerUnavailable(
      `BVNK request was blocked at the edge (CloudFront/WAF, status ${status}) before reaching the API. This is typically IP rate-limiting, not a credential issue; retry shortly or from a different egress.`
    );
  }
  if (status === 401) {
    return providerNotConfigured(
      "BVNK rejected the request credentials (status 401). Check the BVNK Hawk auth configuration."
    );
  }
  if (status === 403) {
    return providerNotConfigured(
      "BVNK request was forbidden (status 403). Check the BVNK Hawk auth/account permissions and that the API egress IP is allowlisted on the merchant account."
    );
  }
  if (status === 409) {
    return conflict(message);
  }
  if (status === 429) {
    return rateLimited(message);
  }
  if (status >= 500) {
    return internalError(`BVNK request failed with status ${status}.`);
  }
  return badRequest(message, options?.details);
}

/**
 * Maps a non-2xx BVNK HTTP response into an SdpPaymentsError, distinguishing edge
 * blocks, auth failures, rate limits, validation errors, and provider-side 5xx failures.
 *
 * @param status - HTTP status BVNK returned.
 * @param raw - Raw response body text, used to detect CloudFront/WAF edge blocks.
 * @param parsed - Parsed response body, when the response was JSON.
 * @returns The typed failure error for the given BVNK response.
 */
export function bvnkRequestFailure(status: number, raw: string, parsed: unknown): SdpPaymentsError {
  const envelope = bvnkErrorEnvelopeSchema.safeParse(parsed);
  const parts = envelope.success
    ? [envelope.data.code, envelope.data.message].filter(
        (part): part is string => part !== undefined
      )
    : [];
  const message =
    parts.length === 0
      ? `BVNK request failed with status ${status}`
      : `BVNK request failed with status ${status}: ${parts.join(" ")}`;
  return mapBvnkErrorStatus(status, message, {
    edgeBlocked: isEdgeBlockBody(parsed, raw),
    details:
      status === 400 && envelope.success && envelope.data.details !== undefined
        ? { errors: envelope.data.details.errors }
        : undefined,
  });
}

/**
 * Parses a BVNK response body against its schema, failing loudly with a
 * provider-unavailable error when the wire shape does not match.
 *
 * @param schema - Zod schema for the expected BVNK response body.
 * @param response - Raw parsed response body.
 * @returns The validated response data.
 */
export function parseBvnkResponse<T extends z.ZodType>(schema: T, response: unknown): z.infer<T> {
  const parsed = schema.safeParse(response);
  if (!parsed.success) {
    throw providerUnavailable("BVNK response is malformed.", {
      provider: "bvnk",
      issues: z.flattenError(parsed.error).fieldErrors,
    });
  }
  return parsed.data;
}
