import type {
  BvnkBankFundingDetails,
  BvnkPaymentRampInstruction,
  SdpEnvironment,
} from "@sdp/types";
import type { RampFiatCurrency } from "@sdp/types/generated/ramp";
import { RAMP_FIAT_CURRENCIES } from "@sdp/types/generated/ramp";
import type { CryptoAssetSymbol } from "@sdp/types/payment-rails";
import { z } from "zod";
import type { CounterpartyRow } from "../../../counterparty";
import { badRequest, internalError } from "../../../errors";
import { hashString } from "../../../hash";
import { readRecord } from "../../../json";

export interface BvnkRuleEntityAddress {
  addressLine1: string;
  addressLine2?: string;
  postalCode?: string;
  city: string;
  countryCode: string;
  /** ISO 3166-1 alpha-2 country; BVNK rule validation rejects a blank `country`. */
  country: string;
  /** ISO 3166-2 region/state code; BVNK requires it for US beneficiaries. */
  stateCode?: string;
}

export type BvnkEntityType = "INDIVIDUAL" | "COMPANY";

/**
 * Beneficiary entity accepted by a BVNK on-ramp payment rule.
 */
export interface BvnkRuleEntity {
  type: BvnkEntityType;
  customerIdentifier: string;
  relationshipType: "SELF_OWNED" | "THIRD_PARTY";
  firstName?: string;
  lastName?: string;
  dateOfBirth?: string;
  legalName?: string;
  registrationNumber?: string;
  address?: BvnkRuleEntityAddress;
}

export const BVNK_NETWORKS = ["SOLANA"] as const;

export type BvnkNetwork = (typeof BVNK_NETWORKS)[number];

export const BVNK_CRYPTO_CURRENCIES = [
  "SOL",
  "USDC",
  "USDT",
] as const satisfies readonly CryptoAssetSymbol[];

export type BvnkCryptoCurrency = (typeof BVNK_CRYPTO_CURRENCIES)[number];

const BVNK_SOLANA_NETWORK_ALIASES = new Set(["sol", "solana"]);
const BVNK_CRYPTO_CURRENCY_SET = new Set<string>(BVNK_CRYPTO_CURRENCIES);

interface BvnkCurrencyNetwork {
  currency: BvnkCryptoCurrency;
  network: BvnkNetwork;
}

export function normalizeBvnkCurrencyAndNetwork(value: string): BvnkCurrencyNetwork {
  const normalized = value.trim().toUpperCase();
  if (!/^[A-Z0-9_]+$/.test(normalized)) {
    throw badRequest("cryptoToken must be a valid BVNK currency code");
  }

  const tokenParts = normalized.split("_").filter((part) => part.length > 0);
  const currency = tokenParts[0];
  if (!currency) {
    throw badRequest("cryptoToken must include a BVNK currency code");
  }

  const networkHint = tokenParts.length > 1 ? tokenParts[tokenParts.length - 1]?.toLowerCase() : "";
  if (networkHint && BVNK_SOLANA_NETWORK_ALIASES.has(networkHint)) {
    if (BVNK_CRYPTO_CURRENCY_SET.has(currency)) {
      return { currency: currency as BvnkCryptoCurrency, network: "SOLANA" };
    }
  }
  if (BVNK_CRYPTO_CURRENCY_SET.has(currency)) {
    return { currency: currency as BvnkCryptoCurrency, network: "SOLANA" };
  }

  throw badRequest(
    `Unsupported BVNK cryptoToken '${value}'. SDP BVNK ramps only support Solana assets (for example: SOL, USDC_SOLANA).`
  );
}

/**
 * Builds BVNK's `Idempotency-Key` header for fiat wallet creation.
 *
 * SDP's BVNK wallet `name` is the canonical wallet identity. BVNK caps
 * idempotency keys at 36 characters, so SDP hashes the full wallet name and
 * trims the digest to the provider limit instead of sending the long readable
 * name as the key.
 *
 * @param walletName BVNK wallet `name` generated by SDP.
 * @returns A stable 36-character idempotency key for the wallet name.
 */
export async function buildBvnkWalletIdempotencyKey(walletName: string): Promise<string> {
  return (await hashString(walletName)).slice(0, 36);
}

/**
 * Builds the caller-defined BVNK off-ramp channel reference.
 *
 * The route pre-generates the SDP payment transfer id before creating the BVNK
 * channel, then persists the transfer with that same id after BVNK returns the
 * channel uuid. This keeps BVNK's human/provider-side reference tied to SDP's
 * transaction id.
 *
 * BVNK rejects `reference` values containing colons or other special
 * characters; allowed characters are alphanumeric characters, dashes,
 * underscores, and periods. This deliberately uses underscores instead of the
 * wallet-name convention (`sdp:offramp:...`) so the reference is accepted by
 * BVNK while still carrying SDP's transfer id.
 *
 * @param paymentTransferId SDP payment transfer id, for example `xfr_<uuid>`.
 * @returns BVNK off-ramp reference in `sdp_offramp_<transfer_id>` format.
 */
export function buildBvnkOfframpReference(paymentTransferId: string): string {
  if (!paymentTransferId.trim()) {
    throw internalError("BVNK off-ramp reference requires a payment transfer id.");
  }
  return `sdp_offramp_${paymentTransferId}`;
}

/**
 * Parses BVNK's channel transaction `data.reference` back into the SDP transfer id.
 *
 * @param reference BVNK off-ramp reference in `sdp_offramp_<transfer_id>` format.
 * @returns SDP payment transfer id (for example `xfr_<uuid>`), or undefined for a
 * channel payment SDP did not create — BVNK also delivers webhooks for foreign
 * transactions (sandbox tests, manual payments), which must be acked and ignored
 * rather than rejected.
 */
export function readBvnkOfframpReference(reference: string): string | undefined {
  const prefix = "sdp_offramp_";
  if (!reference.startsWith(prefix)) {
    return undefined;
  }
  const transferId = reference.slice(prefix.length);
  if (!/^xfr_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(transferId)) {
    return undefined;
  }
  return transferId;
}

/** Per funding-spec (fiat+token+destination) virtual wallet + rule. */
export interface BvnkOnrampRequestSpec {
  currency: BvnkCryptoCurrency;
  network: BvnkNetwork;
  destinationWalletAddress: string;
  fiatCurrency: RampFiatCurrency;
}

export interface BvnkOnrampPaymentRuleState {
  walletId?: string;
  walletName?: string;
  walletStatus?: string;
  ruleId?: string;
  ruleStatus?: string;
  bankAccount?: BvnkBankFundingDetails;
  request?: BvnkOnrampRequestSpec;
  provisioningError?: string;
}

const BVNK_WALLET_ACTIVE_STATUSES = new Set(["ACTIVE", "COMPLETED"]);

export function isBvnkWalletActive(status: string | undefined): boolean {
  return status !== undefined && BVNK_WALLET_ACTIVE_STATUSES.has(status.toUpperCase());
}

export interface BvnkPaymentRuleResolution {
  entry: BvnkOnrampPaymentRuleState;
  onboardingStatus: "ready" | "provisioning";
}

export function readBvnkData(
  providerData: CounterpartyRow["provider_data"]
): Record<string, unknown> {
  const bvnk = providerData.bvnk;
  return bvnk && typeof bvnk === "object" ? (bvnk as Record<string, unknown>) : {};
}

export function readBvnkWallets(
  providerData: CounterpartyRow["provider_data"]
): Record<string, BvnkOnrampPaymentRuleState> {
  const wallets = readBvnkData(providerData).wallets;
  return wallets && typeof wallets === "object"
    ? (wallets as Record<string, BvnkOnrampPaymentRuleState>)
    : {};
}

export function withBvnkOnrampPaymentRuleState(
  providerData: CounterpartyRow["provider_data"],
  onrampPaymentRuleKey: string,
  paymentRule: Partial<BvnkOnrampPaymentRuleState>
): CounterpartyRow["provider_data"] {
  const bvnk = readBvnkData(providerData);
  const wallets = readBvnkWallets(providerData);
  return {
    ...providerData,
    bvnk: {
      ...bvnk,
      wallets: {
        ...wallets,
        [onrampPaymentRuleKey]: {
          ...wallets[onrampPaymentRuleKey],
          ...paymentRule,
        },
      },
    },
  };
}

export function pendingBvnkOnrampPaymentRuleKeys(
  providerData: CounterpartyRow["provider_data"]
): string[] {
  return Object.entries(readBvnkWallets(providerData))
    .filter(([, entry]) => entry.request && !entry.ruleId)
    .map(([key]) => key);
}

/** Merchant-owned BVNK off-ramp wallet, one per fiat currency. */
export interface BvnkOfframpWallet {
  id: string;
  status?: string;
}

export function buildBvnkOfframpWalletName(
  fiatCurrency: RampFiatCurrency,
  counterpartyId: string
): string {
  return `sdp:offramp:${fiatCurrency}:${counterpartyId}`;
}

/**
 * Builds the BVNK wallet name for customer-owned on-ramp funding wallets.
 *
 * The name carries the SDP counterparty id and the deterministic on-ramp
 * payment rule fields so wallet lifecycle webhooks can update
 * `provider_data.bvnk.wallets[onrampPaymentRuleKey]` directly.
 *
 * @param counterpartyId SDP counterparty primary key.
 * @param onrampPaymentRuleKey Deterministic key from `buildBvnkOnrampPaymentRuleKey`.
 * @returns BVNK wallet name in
 * `sdp:onramp:<counterparty_id>:<fiat>:<crypto>_<network>:<destination>` format.
 */
export function buildBvnkOnrampWalletName(
  counterpartyId: string,
  onrampPaymentRuleKey: string
): string {
  const key = parseBvnkOnrampPaymentRuleKey(onrampPaymentRuleKey);
  return `sdp:onramp:${counterpartyId}:${key.fiatCurrency}:${key.cryptoCurrency}_${key.cryptoNetwork}:${key.destinationWalletAddress}`;
}

const BVNKOfframpWalletName = z.object({
  namespace: z.literal("sdp"),
  direction: z.literal("offramp"),
  fiatCurrency: z.enum(RAMP_FIAT_CURRENCIES),
  counterpartyId: z.string().min(1),
});

const BVNKOnrampWalletName = z.object({
  namespace: z.literal("sdp"),
  direction: z.literal("onramp"),
  counterpartyId: z.string().min(1),
  onrampKey: z.string().min(1),
});

export const BVNKWallet = z.discriminatedUnion("direction", [
  BVNKOfframpWalletName,
  BVNKOnrampWalletName,
]);

export type BVNKWallet = z.infer<typeof BVNKWallet>;

export function parseBvnkOfframpWalletName(
  walletName: string
): Extract<BVNKWallet, { direction: "offramp" }> {
  const parts = walletName.split(":");
  if (parts.length !== 4) {
    throw internalError(`Malformed BVNK off-ramp wallet name: ${walletName}`);
  }
  const [namespace, direction, fiatCurrency, counterpartyId] = parts;
  const parsed = BVNKOfframpWalletName.safeParse({
    namespace,
    direction,
    fiatCurrency,
    counterpartyId,
  });
  if (!parsed.success) {
    throw internalError(`Malformed BVNK off-ramp wallet name: ${walletName}`);
  }
  return parsed.data;
}

/**
 * Parses a customer-owned BVNK funding wallet name back into its SDP owner and
 * on-ramp entry key.
 *
 * @param walletName BVNK wallet `name` value.
 * @returns Parsed SDP counterparty id and `buildBvnkOnrampPaymentRuleKey` value.
 * @throws SdpPaymentsError with `INTERNAL_ERROR` when the name does not match the SDP
 * on-ramp wallet naming contract.
 */
export function parseBvnkOnrampWalletName(
  walletName: string
): Extract<BVNKWallet, { direction: "onramp" }> {
  const parts = walletName.split(":");
  if (parts.length !== 6) {
    throw internalError(`Malformed BVNK on-ramp wallet name: ${walletName}`);
  }
  const [namespace, direction, counterpartyId, fiatCurrency, cryptoRail, destinationWalletAddress] =
    parts;
  let onrampKey = `${fiatCurrency}:${cryptoRail}:${destinationWalletAddress}`;
  try {
    const key = parseBvnkOnrampPaymentRuleKey(onrampKey);
    onrampKey = buildBvnkOnrampPaymentRuleKey(
      key.fiatCurrency,
      key.cryptoCurrency,
      key.cryptoNetwork,
      key.destinationWalletAddress
    );
  } catch {
    throw internalError(`Malformed BVNK on-ramp wallet name: ${walletName}`);
  }
  const parsed = BVNKOnrampWalletName.safeParse({
    namespace,
    direction,
    counterpartyId,
    onrampKey,
  });
  if (!parsed.success) {
    throw internalError(`Malformed BVNK on-ramp wallet name: ${walletName}`);
  }
  return parsed.data;
}

/**
 * Parses an SDP-created BVNK wallet name into its logical wallet reference.
 *
 * @param walletName BVNK wallet `name` value.
 * @returns The parsed on-ramp or off-ramp wallet reference.
 * @throws SdpPaymentsError with `INTERNAL_ERROR` when the name does not match the
 * SDP BVNK wallet naming contract.
 */
export function parseBvnkWalletName(walletName: string): BVNKWallet {
  const parts = walletName.split(":");
  switch (parts[1]) {
    case "offramp":
      return parseBvnkOfframpWalletName(walletName);
    case "onramp":
      return parseBvnkOnrampWalletName(walletName);
    default:
      throw internalError(`Malformed BVNK wallet name: ${walletName}`);
  }
}

export function readBvnkOfframpWallets(
  providerData: CounterpartyRow["provider_data"]
): Record<string, BvnkOfframpWallet> {
  const offramp = readRecord(readBvnkData(providerData).offramp)?.wallets;
  return offramp && typeof offramp === "object"
    ? (offramp as Record<string, BvnkOfframpWallet>)
    : {};
}

export function withBvnkOfframpWalletStatus(
  providerData: CounterpartyRow["provider_data"],
  fiatCurrency: RampFiatCurrency,
  status: string
): CounterpartyRow["provider_data"] {
  const bvnk = readBvnkData(providerData);
  const offramp =
    bvnk.offramp && typeof bvnk.offramp === "object"
      ? (bvnk.offramp as Record<string, unknown>)
      : {};
  const wallets = readBvnkOfframpWallets(providerData);
  return {
    ...providerData,
    bvnk: {
      ...bvnk,
      offramp: {
        ...offramp,
        wallets: {
          ...wallets,
          [fiatCurrency]: { ...wallets[fiatCurrency], status },
        },
      },
    },
  };
}

export function readBvnkOfframpWallet(
  providerData: CounterpartyRow["provider_data"],
  fiatCurrency: string
): BvnkOfframpWallet | undefined {
  return readBvnkOfframpWallets(providerData)[fiatCurrency];
}

/** A registered off-ramp payout beneficiary. PII-light: raw account details are not stored. */
export interface BvnkOfframpBeneficiary {
  /** `${fiatCurrency}:${hash(collectedData)}` — content-addressed so distinct bank details never collide. */
  key: string;
  fiatCurrency: string;
  accountType: string;
  createdAt: string;
}

export function readBvnkOfframpBeneficiaries(
  providerData: CounterpartyRow["provider_data"]
): Record<string, unknown> {
  const beneficiaries = readRecord(readBvnkData(providerData).offramp)?.beneficiaries;
  return beneficiaries && typeof beneficiaries === "object"
    ? (beneficiaries as Record<string, unknown>)
    : {};
}

function parseBvnkOfframpBeneficiary(key: string, value: unknown): BvnkOfframpBeneficiary {
  const { fiatCurrency, accountType, createdAt } = value as {
    fiatCurrency?: unknown;
    accountType?: unknown;
    createdAt?: unknown;
  };
  if (
    typeof fiatCurrency !== "string" ||
    typeof accountType !== "string" ||
    typeof createdAt !== "string"
  ) {
    throw internalError(`Malformed BVNK off-ramp beneficiary "${key}" in provider_data`);
  }
  return { key, fiatCurrency, accountType, createdAt };
}

export function readBvnkOfframpBeneficiaryByKey(
  providerData: CounterpartyRow["provider_data"],
  key: string
): BvnkOfframpBeneficiary | null {
  const value = readBvnkOfframpBeneficiaries(providerData)[key];
  return value === undefined ? null : parseBvnkOfframpBeneficiary(key, value);
}

export function latestBvnkOfframpBeneficiary(
  providerData: CounterpartyRow["provider_data"],
  fiatCurrency: string
): BvnkOfframpBeneficiary | null {
  const entries = Object.entries(readBvnkOfframpBeneficiaries(providerData))
    .filter(([key]) => key.startsWith(`${fiatCurrency}:`))
    .map(([key, value]) => parseBvnkOfframpBeneficiary(key, value))
    .sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  return entries[0] ?? null;
}

/**
 * Schema for the logical components encoded into
 * `provider_data.bvnk.wallets[onrampPaymentRuleKey]`.
 */
export const BVNKOnrampPaymentRuleKey = z.object({
  fiatCurrency: z.enum(RAMP_FIAT_CURRENCIES),
  cryptoCurrency: z.enum(BVNK_CRYPTO_CURRENCIES),
  cryptoNetwork: z.enum(BVNK_NETWORKS),
  destinationWalletAddress: z
    .string()
    .min(1)
    .refine((value) => !value.includes(":")),
});

export type BVNKOnrampPaymentRuleKey = z.infer<typeof BVNKOnrampPaymentRuleKey>;

/**
 * Builds the deterministic key for a BVNK on-ramp payment rule.
 *
 * This key identifies the exact funding rule SDP needs for one fiat funding
 * currency, one crypto asset/network destination, and one destination wallet.
 * It is stored under `provider_data.bvnk.wallets` and embedded into the BVNK
 * wallet name so webhook handlers can reverse it without scanning by wallet id.
 *
 * @param fiatCurrency Fiat currency the counterparty sends into the BVNK funding account.
 * @param cryptoCurrency Crypto asset BVNK delivers for the on-ramp, such as `USDC`.
 * @param cryptoNetwork Blockchain network BVNK delivers on, such as `SOLANA`.
 * @param destinationWalletAddress Destination wallet address that receives the on-ramped crypto.
 * @returns Serialized on-ramp payment rule key in `<fiat>:<crypto>_<network>:<destination>` format.
 * @throws SdpPaymentsError with `INTERNAL_ERROR` when inputs do not satisfy the SDP key contract.
 */
export function buildBvnkOnrampPaymentRuleKey(
  fiatCurrency: RampFiatCurrency,
  cryptoCurrency: BvnkCryptoCurrency,
  cryptoNetwork: BvnkNetwork,
  destinationWalletAddress: string
): string {
  const parsed = BVNKOnrampPaymentRuleKey.safeParse({
    fiatCurrency,
    cryptoCurrency,
    cryptoNetwork,
    destinationWalletAddress,
  });
  if (!parsed.success) {
    throw internalError("Malformed BVNK on-ramp payment rule key input");
  }
  return `${parsed.data.fiatCurrency}:${parsed.data.cryptoCurrency}_${parsed.data.cryptoNetwork}:${parsed.data.destinationWalletAddress}`;
}

/**
 * Parses a stored BVNK on-ramp payment rule key back to its logical components.
 *
 * @param key Serialized key from `buildBvnkOnrampPaymentRuleKey`.
 * @returns Parsed fiat funding currency, on-ramped crypto asset/network, and destination wallet.
 * @throws SdpPaymentsError with `INTERNAL_ERROR` when the key no longer matches SDP's BVNK key contract.
 */
export function parseBvnkOnrampPaymentRuleKey(key: string): BVNKOnrampPaymentRuleKey {
  const parts = key.split(":");
  if (parts.length !== 3) {
    throw internalError(`Malformed BVNK on-ramp payment rule key: ${key}`);
  }
  const [fiatCurrency, cryptoRail, destinationWalletAddress] = parts;
  if (!cryptoRail.endsWith("_SOLANA")) {
    throw internalError(`Malformed BVNK on-ramp payment rule key: ${key}`);
  }
  const cryptoNetwork: BvnkNetwork = "SOLANA";
  const cryptoCurrency = cryptoRail.slice(0, -"_SOLANA".length);
  const parsed = BVNKOnrampPaymentRuleKey.safeParse({
    fiatCurrency,
    cryptoCurrency,
    cryptoNetwork,
    destinationWalletAddress,
  });
  if (!parsed.success) {
    throw internalError(`Malformed BVNK on-ramp payment rule key: ${key}`);
  }
  return parsed.data;
}

export function readBvnkOnrampPaymentRuleState(
  providerData: CounterpartyRow["provider_data"],
  key: string
): BvnkOnrampPaymentRuleState {
  const entry = readBvnkWallets(providerData)[key];
  return entry && typeof entry === "object" ? entry : {};
}

export async function bvnkRuleReference(
  counterpartyId: string,
  onrampKey: string
): Promise<string> {
  return (await hashString(`bvnk-rule:${counterpartyId}:${onrampKey}`)).slice(0, 36);
}

/**
 * Builds the fiat-funding instruction for an on-ramp quote from the stored
 * wallet/rule entry. The Direct model keys identity on a BVNK contact rather
 * than customer KYC, so the instruction note is the standing funding call to
 * action and never branches on onboarding state.
 *
 * @param resolution - Stored funding-wallet entry for the payment rule.
 * @param params - Network, destination wallet, fiat currency, and environment.
 * @returns The typed fiat-funding instruction with the merchant funding details.
 */
export function buildBvnkOnrampInstruction(
  resolution: { entry: BvnkOnrampPaymentRuleState },
  params: {
    network: string;
    destinationWalletAddress: string;
    fiatCurrency: string;
    mode: SdpEnvironment;
  }
): BvnkPaymentRampInstruction {
  const { entry } = resolution;
  return {
    provider: "bvnk",
    kind: "fiat_funding",
    ruleId: entry.ruleId,
    ruleStatus: entry.ruleStatus,
    fundingWalletId: entry.walletId,
    fiatCurrency: params.fiatCurrency,
    beneficiaryAddress: params.destinationWalletAddress,
    network: params.network,
    bankAccount: entry.bankAccount,
    instructionsNotes: `Fund your ${params.fiatCurrency} BVNK virtual account to receive crypto on ${params.network}.`,
  };
}

/**
 * Resolves stored BVNK wallet/rule state into the on-ramp provisioning
 * resolution. No customer gating: the funding-wallet entry alone decides
 * between `ready` (rule and bank account present) and `provisioning`.
 *
 * @param providerData - Stored wallet and rule state.
 * @param params - Funding specification for the on-ramp.
 * @returns The pure provisioning resolution.
 */
export function bvnkOnrampPaymentRuleResolutionFromProviderData(
  providerData: CounterpartyRow["provider_data"],
  params: { cryptoToken: string; fiatCurrency: RampFiatCurrency; destinationWalletAddress: string }
): BvnkPaymentRuleResolution {
  const { currency, network } = normalizeBvnkCurrencyAndNetwork(params.cryptoToken);
  const key = buildBvnkOnrampPaymentRuleKey(
    params.fiatCurrency,
    currency,
    network,
    params.destinationWalletAddress
  );
  const entry = readBvnkOnrampPaymentRuleState(providerData, key);
  return {
    entry,
    onboardingStatus: entry.ruleId && entry.bankAccount?.accountNumber ? "ready" : "provisioning",
  };
}
